allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@superdoc/sdk-darwin-arm64@2.16.0-next.8'
  - '@superdoc/sdk-darwin-x64@2.16.0-next.8'
  - '@superdoc/sdk-linux-arm64@2.16.0-next.8'
  - '@superdoc/sdk-linux-x64@2.16.0-next.8'
  - '@superdoc/sdk-windows-x64@2.16.0-next.8'
  - '@superdoc/sdk@2.16.0-next.8'
